# Este es nuestro primerplaybook
- name: "primera play"
  hosts: all
  gather_facts: true

  tasks:
  - name: "comprobar conexion"
    ping:
      data: funcionando

- name: "segunda play"
  become: yes
  hosts: servidor_web
  tags: segunda_play
  gather_facts: true
  vars:
    state: latest

  tasks:
  - name: "listar directorios"
    command: ls
    register: contenido
    tags: 
      - listar
    ignore_errors: yes
  
  - name: "comprobar ficheros"
    debug:
      msg: "El directorio no esta vacio"
    when: contenido.stdout != ""


  - name: "instalar Nginx"
    apt: name=nginx state={{state}}
    notify: restart nginx

  - name: "copiar index en app" 
    copy:
      src: index.html
      dest: /var/www/html

- name: "tercera play"
  hosts: all
  become: yes
  tags: tercera_play
  vars:
    version: "5.14"
    servidor: "Ubuntu"
    coches: ['Mercedes', 'Nissan', 'Toyota']
  
  tasks:
  - name: "Imprimir template"
    template:
      src: template_1.j2
      dest: /home/ansible/archivo_1.txt

  - name: "Loop templates"
    template:
      src: template_2.j2
      dest: /home/ansible/archivo_2.txt

  - name: "Mostrar un nuevo fichero"
    template:
      src: template_3.j2
      dest: /var/www/html/index.html
      mode: 0755

  handlers:
  - name: "restart nginx"
    service: 
      name: nginx
      state: restarted