# Este es nuestro primerplaybook
- name: "primera play"
  hosts: all
  gather_facts: true

  tasks:
  - name: "comprobar conexion"
    ping:
      data: funcionando

- name: "segunda play"
  become: yes
  hosts: servidor_web
  gather_facts: true
  vars:
    state: latest

  tasks:
  - name: "listar directorios"
    command: ls
    register: contenido
  
  - name: "comprobar ficheros"
    debug:
      msg: "El directorio no esta vacio"
    when: contenido.stdout != ""


  - name: "instalar Nginx"
    apt: name=nginx state={{state}}
    notify: restart nginx

  - name: "copiar index en app" 
    copy:
      src: index.html
      dest: /var/www/html

  handlers:
  - name: "restart nginx"
    service: 
      name: nginx
      state: restarted